nats:
  protocol: "nats"
  address: "localhost"
  port: "4221"
  credential:
    user: "mq_user"
    password: "strong_password123"
  connection_name: "notification_service_conn"
  timeout: 10

jetstream:
  stream:
    name: "log_stream"
    description: "this is log stream"
  consumer:
    log: "log_consumer"
  subject:
    global: "log.>"
    log: "log.*"

otel:
  endpoint: "http://localhost:9428/insert/opentelemetry/v1/logs"
